"""Sanity checks on the data files that ship inside the package.

``elite_hud/data/exobiology.json`` is generated by a tool rather than hand
written, so these tests guard against a truncated or subtly broken rebuild.
"""

from __future__ import annotations

import json
import unittest
from pathlib import Path

DATA = Path(__file__).parent.parent / "elite_hud" / "data" / "exobiology.json"

#: Spot values cross-checked against Canonn Research sales data and the
#: ArtemisScannerTracker "Update 14.01" table.
KNOWN_VALUES = {
    "Stratum Tectonicas": 19_010_800,
    "Fonticulua Fluctus": 20_000_000,
    "Tussock Stigmasis": 19_010_800,
    "Bacterium Aurasus": 1_000_000,
    "Clypeus Lacrimam": 8_418_000,
    "Recepta Umbrux": 12_934_900,
    "Tubus Conifer": 2_415_500,
}

#: BioScan still ships the pre-Update-14 2**24-1 placeholder; the builder
#: corrects it, and this test makes sure the correction is not lost.
CORRECTIONS = {"Concha Biconcavis": 19_010_800}

#: Horizons-era curiosities with no Vista Genomics payout.
NON_SELLABLE = (
    "Roseum Brain Tree",
    "Luteolum Anemone",
    "Viride Sinuous Tubers",
    "Crystalline Shards",
    "Bark Mound",
    "Amphora Plant",
)


class ExobiologyDataTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.payload = json.loads(DATA.read_text(encoding="utf-8"))

    def test_file_is_present_and_complete(self) -> None:
        self.assertGreaterEqual(len(self.payload["genera"]), 18)
        self.assertGreaterEqual(len(self.payload["by_name"]), 80)

    def test_known_values(self) -> None:
        by_name = self.payload["by_name"]
        for name, value in {**KNOWN_VALUES, **CORRECTIONS}.items():
            with self.subTest(species=name):
                self.assertEqual(by_name.get(name), value)

    def test_every_genus_has_a_display_name(self) -> None:
        for key, genus in self.payload["genera"].items():
            with self.subTest(genus=key):
                self.assertTrue(genus["name"], "genus has no display name")
                self.assertTrue(genus["species"], "genus has no species")

    def test_value_envelope_matches_the_species(self) -> None:
        for key, genus in self.payload["genera"].items():
            values = [s["value"] for s in genus["species"].values() if s["value"] > 0]
            if not values:
                continue
            with self.subTest(genus=key):
                self.assertEqual(genus["min_value"], min(values))
                self.assertEqual(genus["max_value"], max(values))

    def test_sellable_genera_never_contain_zero_value_species(self) -> None:
        for key, genus in self.payload["genera"].items():
            if not genus["sellable"]:
                continue
            for species_key, species in genus["species"].items():
                with self.subTest(genus=key, species=species_key):
                    self.assertGreater(species["value"], 0)

    def test_non_sellable_organics_are_absent_from_the_lookup(self) -> None:
        by_name = self.payload["by_name"]
        by_key = self.payload["by_key"]
        for name in NON_SELLABLE:
            with self.subTest(species=name):
                self.assertNotIn(name, by_name)
        # And their codex symbols must not resolve either.
        blocked = set()
        for genus in self.payload["genera"].values():
            if genus["sellable"]:
                continue
            blocked.update(genus["species"].keys())
        self.assertFalse(blocked & set(by_key), "a non-sellable species kept its codex key")

    def test_no_placeholder_2_pow_24_values_remain(self) -> None:
        placeholder = 2**24 - 1
        offenders = [
            name for name, value in self.payload["by_name"].items() if value == placeholder
        ]
        self.assertEqual(offenders, [], "an uncorrected 2**24-1 placeholder is still present")

    def test_codex_keys_look_like_codex_keys(self) -> None:
        for key in self.payload["by_key"]:
            with self.subTest(key=key):
                self.assertTrue(key.startswith("$Codex_Ent_"), key)
                self.assertTrue(key.endswith(";"), key)


if __name__ == "__main__":
    unittest.main()
