"""Build the Windows executable with PyInstaller.

    python tools/build_exe.py                 # onedir bundle (used by the installer)
    python tools/build_exe.py --onefile       # single self-contained .exe
    python tools/build_exe.py --windowed      # hide the console window

``onedir`` is the default: it starts noticeably faster (no per-launch temp
extraction), keeps the release zip smaller, and makes self-update a plain file
copy instead of replacing a running single-file bundle.
"""

from __future__ import annotations

import argparse
import ast
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SEP = ";" if sys.platform == "win32" else ":"
ICON = REPO_ROOT / "installer" / "elite-hud.ico"

#: Qt modules the HUD never touches; excluding them shrinks the bundle a lot.
EXCLUDED_QT_MODULES = (
    "PySide6.QtWebEngineCore",
    "PySide6.QtWebEngineWidgets",
    "PySide6.QtWebEngineQuick",
    "PySide6.QtQuick",
    "PySide6.QtQuick3D",
    "PySide6.QtQml",
    "PySide6.Qt3DCore",
    "PySide6.Qt3DRender",
    "PySide6.Qt3DAnimation",
    "PySide6.Qt3DExtras",
    "PySide6.QtCharts",
    "PySide6.QtDataVisualization",
    "PySide6.QtMultimedia",
    "PySide6.QtMultimediaWidgets",
    "PySide6.QtBluetooth",
    "PySide6.QtDesigner",
    "PySide6.QtHelp",
    "PySide6.QtPdf",
    "PySide6.QtSql",
    "PySide6.QtTest",
    "PySide6.QtOpenGL",
    "PySide6.QtSensors",
    "PySide6.QtSerialPort",
    "PySide6.QtWebChannel",
    "PySide6.QtWebSockets",
)
EXCLUDED_MODULES = ("tkinter", "pydoc", "doctest")


def project_version() -> str:
    """Read ``__version__`` without importing the package (no Qt import)."""
    source = (REPO_ROOT / "elite_hud" / "__init__.py").read_text(encoding="utf-8")
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "__version__":
                    return ast.literal_eval(node.value)
    raise SystemExit("could not find __version__ in elite_hud/__init__.py")


def write_version_resource(version: str, destination: Path) -> Path:
    """Emit a PyInstaller version resource so Explorer shows real metadata."""
    numbers = [int(part) for part in version.split("-")[0].split(".")]
    numbers += [0] * (4 - len(numbers))
    tuple_text = ", ".join(str(n) for n in numbers[:4])
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        f"""# Generated by tools/build_exe.py -- do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({tuple_text}),
    prodvers=({tuple_text}),
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'madne5'),
        StringStruct('FileDescription', 'elite-hud - Elite Dangerous journal HUD overlay'),
        StringStruct('FileVersion', '{version}'),
        StringStruct('InternalName', 'elite-hud'),
        StringStruct('OriginalFilename', 'elite-hud.exe'),
        StringStruct('ProductName', 'elite-hud'),
        StringStruct('ProductVersion', '{version}'),
        StringStruct('LegalCopyright', 'MIT licensed'),
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
""",
        encoding="utf-8",
    )
    return destination


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--windowed", action="store_true", help="hide the console window")
    parser.add_argument("--onefile", action="store_true", help="single-file executable")
    parser.add_argument("--name", default="elite-hud", help="executable name")
    parser.add_argument("--clean", action="store_true", help="remove build/ and dist/ first")
    parser.add_argument("--no-icon", action="store_true", help="skip the generated icon")
    options = parser.parse_args()

    if shutil.which("pyinstaller") is None:
        print(
            "pyinstaller not found. Install it first:\n"
            f"    {sys.executable} -m pip install pyinstaller",
            file=sys.stderr,
        )
        return 2

    data_file = REPO_ROOT / "elite_hud" / "data" / "exobiology.json"
    if not data_file.is_file():
        print(
            f"missing {data_file}; run tools/build_exobiology_data.py first",
            file=sys.stderr,
        )
        return 2

    version = project_version()
    if options.clean:
        for directory in ("build", "dist"):
            shutil.rmtree(REPO_ROOT / directory, ignore_errors=True)

    version_file = write_version_resource(version, REPO_ROOT / "build" / "version_info.txt")

    command = [
        "pyinstaller",
        "--noconfirm",
        "--name",
        options.name,
        "--paths",
        str(REPO_ROOT),
        "--add-data",
        f"{data_file}{SEP}elite_hud/data",
        "--version-file",
        str(version_file),
        # Qt loads these dynamically, so PyInstaller cannot see them.
        "--hidden-import",
        "PySide6.QtCore",
        "--hidden-import",
        "PySide6.QtGui",
        "--hidden-import",
        "PySide6.QtWidgets",
    ]
    command.append("--onefile" if options.onefile else "--onedir")
    command.append("--windowed" if options.windowed else "--console")

    if not options.no_icon and ICON.is_file():
        command += ["--icon", str(ICON)]

    for module in (*EXCLUDED_QT_MODULES, *EXCLUDED_MODULES):
        command += ["--exclude-module", module]

    command.append(str(REPO_ROOT / "elite_hud" / "__main__.py"))

    print(f"building elite-hud {version}")
    print("running:", " ".join(command))
    result = subprocess.run(command, cwd=REPO_ROOT, check=False)
    if result.returncode != 0:
        return result.returncode

    target = REPO_ROOT / "dist" / (options.name + (".exe" if options.onefile else ""))
    print(f"\nbuilt: {target}")
    if not options.onefile:
        print(f"runtime files: {REPO_ROOT / 'dist' / options.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
